"use client";

import { useEffect, useState } from "react";
import type {
  Scenario,
  BenchmarkResult,
  DetectorEntry,
  Attestation,
  VerifyResult,
} from "@/lib/core";

type RunResponse = {
  seed: number;
  count: number;
  fraction: number;
  provider: string;
  scenarios: Scenario[];
  benchmark: BenchmarkResult;
  metering?: { metered: boolean; reason?: string };
};

const pct = (x: number) => `${(x * 100).toFixed(0)}%`;
const usd = (nano: number) => `$${(nano / 1e9).toFixed(6)}`;
const spoofingOf = (d: DetectorEntry) =>
  d.metrics.by_type.spoofing ?? { caught: 0, total: 0 };

export default function Home() {
  const [seed, setSeed] = useState(7);
  const [count, setCount] = useState(10);
  const [fraction, setFraction] = useState(0.4);
  const [provider, setProvider] = useState<"stub" | "flock">("stub");

  const [data, setData] = useState<RunResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selectedMiss, setSelectedMiss] = useState<string | null>(null);

  async function runBenchmark() {
    setLoading(true);
    setError(null);
    setSelectedMiss(null);
    try {
      const res = await fetch("/api/run", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ seed, count, fraction, provider }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.stderr || json.error || "run failed");
      setData(json as RunResponse);
    } catch (e) {
      setError((e as Error).message);
      setData(null);
    } finally {
      setLoading(false);
    }
  }

  const scenarioById = (id: string) =>
    data?.scenarios.find((s) => s.scenario_id === id);

  return (
    <main className="mx-auto max-w-6xl px-5 py-10">
      <Header />

      <MarketReference />

      <Controls
        seed={seed} setSeed={setSeed}
        count={count} setCount={setCount}
        fraction={fraction} setFraction={setFraction}
        provider={provider} setProvider={setProvider}
        loading={loading} onRun={runBenchmark}
      />

      {error && (
        <div className="mt-6 rounded-lg border border-red-500/40 bg-red-500/10 p-4 text-sm text-red-200">
          <span className="font-semibold">Core error:</span>{" "}
          <span className="mono">{error}</span>
        </div>
      )}

      {data && (
        <>
          <section className="mt-8 grid grid-cols-1 gap-4 md:grid-cols-2">
            {data.benchmark.detectors.map((d) => (
              <DetectorCard key={d.detector_id} d={d} />
            ))}
          </section>

          <RunMeta benchmark={data.benchmark} provider={data.provider} metering={data.metering} />

          <MissPanel
            detectors={data.benchmark.detectors}
            selected={selectedMiss}
            onSelect={setSelectedMiss}
            scenario={selectedMiss ? scenarioById(selectedMiss) : undefined}
          />

          <WalrusPanel seed={seed} count={count} fraction={fraction} />
        </>
      )}

      <ModelCatalog provider={provider} />

      <footer className="mt-16 border-t border-white/5 pt-6 text-xs text-white/30">
        ProvingGround — validation infrastructure for market-surveillance models. Core
        generated by Codeplain; head-to-head via FLock; tamper-evident record on Walrus.
      </footer>
    </main>
  );
}

type MarketRef = {
  pool: string; mid: number; best_bid: number; best_ask: number;
  spread: number; spread_bps: number; bid_depth: number; ask_depth: number;
  source: string; error?: string;
};

function MarketReference() {
  const [m, setM] = useState<MarketRef | null>(null);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    fetch("/api/market")
      .then((r) => r.json())
      .then((j) => { if (!active) return; if (j.error) setErr(j.error); else setM(j as MarketRef); })
      .catch((e) => active && setErr(String(e)));
    return () => { active = false; };
  }, []);

  return (
    <div className="mt-6 rounded-xl border border-white/10 bg-white/[0.02] px-5 py-3">
      <div className="flex flex-wrap items-center gap-x-6 gap-y-1 text-xs">
        <span className="flex items-center gap-2 text-white/50">
          <span className="inline-block h-1.5 w-1.5 rounded-full bg-emerald-400" />
          live market reference · <span className="mono text-white/70">DeepBook SUI/USDC</span>
        </span>
        {m ? (
          <>
            <span className="text-white/40">mid <span className="mono text-white/80">${m.mid.toFixed(5)}</span></span>
            <span className="text-white/40">spread <span className="mono text-white/80">{m.spread_bps.toFixed(1)} bps</span></span>
            <span className="text-white/40">depth <span className="mono text-white/80">{Math.round(m.bid_depth).toLocaleString()} bid / {Math.round(m.ask_depth).toLocaleString()} ask</span></span>
            <span className="ml-auto text-white/25">scenarios are calibrated against this live book</span>
          </>
        ) : (
          <span className="text-white/30">{err ? "DeepBook unavailable" : "loading live book…"}</span>
        )}
      </div>
    </div>
  );
}

function Header() {
  return (
    <header>
      <div className="flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-sky-300/70">
        <span className="inline-block h-2 w-2 rounded-full bg-sky-400" />
        Manipulation eval harness
      </div>
      <h1 className="mt-3 text-3xl font-semibold tracking-tight md:text-4xl">
        ProvingGround
      </h1>
      <p className="mt-2 max-w-2xl text-sm leading-relaxed text-white/60">
        The hard problem in manipulation detection isn&apos;t detection — it&apos;s{" "}
        <span className="text-white/90">validation</span>. Real manipulation isn&apos;t
        labelled, so you can&apos;t prove a surveillance model works. ProvingGround
        manufactures labelled order-book reality, runs detectors head-to-head, scores the
        catch rate, and writes a tamper-evident record you can verify.
      </p>
    </header>
  );
}

function Controls(props: {
  seed: number; setSeed: (n: number) => void;
  count: number; setCount: (n: number) => void;
  fraction: number; setFraction: (n: number) => void;
  provider: "stub" | "flock"; setProvider: (p: "stub" | "flock") => void;
  loading: boolean; onRun: () => void;
}) {
  return (
    <div className="mt-8 flex flex-wrap items-end gap-4 rounded-xl border border-white/10 bg-white/[0.03] p-5">
      <Field label="Seed">
        <input type="number" value={props.seed}
          onChange={(e) => props.setSeed(Number(e.target.value))}
          className="input" />
      </Field>
      <Field label="Scenarios">
        <input type="number" min={1} value={props.count}
          onChange={(e) => props.setCount(Number(e.target.value))}
          className="input" />
      </Field>
      <Field label="Manipulated fraction">
        <input type="number" min={0} max={1} step={0.1} value={props.fraction}
          onChange={(e) => props.setFraction(Number(e.target.value))}
          className="input" />
      </Field>
      <Field label="LLM provider">
        <select value={props.provider}
          onChange={(e) => props.setProvider(e.target.value as "stub" | "flock")}
          className="input">
          <option value="stub">stub (offline)</option>
          <option value="flock">flock (live)</option>
        </select>
      </Field>
      <button onClick={props.onRun} disabled={props.loading}
        className="ml-auto rounded-lg bg-sky-500 px-5 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-sky-400 disabled:opacity-50">
        {props.loading ? "Running…" : "Run benchmark"}
      </button>
      <style>{`
        .input { background:#0d1117; border:1px solid rgba(255,255,255,.12); border-radius:8px;
          padding:8px 10px; font-size:13px; width:120px; color:#e6edf3; }
        .input:focus { outline:none; border-color:#38bdf8; }
      `}</style>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="flex flex-col gap-1.5">
      <span className="text-xs font-medium uppercase tracking-wide text-white/40">{label}</span>
      {children}
    </label>
  );
}

function DetectorCard({ d }: { d: DetectorEntry }) {
  const spoof = spoofingOf(d);
  const isLLM = d.detector_id.startsWith("llm");
  return (
    <div className="rounded-xl border border-white/10 bg-white/[0.03] p-5">
      <div className="flex items-center justify-between">
        <span className="mono text-sm text-white/80">{d.detector_id}</span>
        <span className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${isLLM ? "bg-purple-500/15 text-purple-200" : "bg-sky-500/15 text-sky-200"}`}>
          {isLLM ? "LLM" : "heuristic"}
        </span>
      </div>
      <div className="mt-4 flex items-end gap-2">
        <span className="text-4xl font-semibold tabular-nums">{pct(d.metrics.catch_rate)}</span>
        <span className="mb-1 text-sm text-white/50">catch rate</span>
      </div>
      <div className="mt-4 grid grid-cols-3 gap-3 text-sm">
        <Stat label="False positives" value={pct(d.metrics.false_positive_rate)} />
        <Stat label="Precision" value={pct(d.metrics.precision)} />
        <Stat label="Spoofing" value={`${spoof.caught}/${spoof.total}`} />
      </div>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg bg-black/30 px-3 py-2">
      <div className="text-[11px] uppercase tracking-wide text-white/35">{label}</div>
      <div className="mt-0.5 font-semibold tabular-nums">{value}</div>
    </div>
  );
}

function RunMeta({ benchmark, provider, metering }: {
  benchmark: BenchmarkResult;
  provider: string;
  metering?: { metered: boolean; reason?: string };
}) {
  return (
    <div className="mt-4 flex flex-wrap items-center gap-x-6 gap-y-2 rounded-xl border border-white/10 bg-white/[0.02] px-5 py-3 text-xs">
      <span className="text-white/40">
        scenario_set_hash{" "}
        <span className="mono text-white/70">{benchmark.scenario_set_hash.slice(0, 24)}…</span>
      </span>
      <span className="text-white/40">
        LLM cost{" "}
        <span className="mono text-emerald-300">{usd(benchmark.cost_nano_usd)}</span>{" "}
        <span className="text-white/30">({benchmark.cost_nano_usd.toLocaleString()} nano-USD)</span>
      </span>
      <span className="text-white/40">provider <span className="mono text-white/70">{provider}</span></span>
      <span className="text-white/40" title={metering?.reason}>
        metered{" "}
        <span className={`mono ${metering?.metered ? "text-emerald-300" : "text-white/40"}`}>
          {metering?.metered ? "eval_run ✓" : "off"}
        </span>
      </span>
    </div>
  );
}

function MissPanel({ detectors, selected, onSelect, scenario }: {
  detectors: DetectorEntry[];
  selected: string | null;
  onSelect: (id: string | null) => void;
  scenario?: Scenario;
}) {
  const allMisses = detectors.flatMap((d) =>
    d.misses.map((m) => ({ ...m, detector_id: d.detector_id })),
  );

  return (
    <section className="mt-8">
      <h2 className="text-lg font-semibold">Misses — what the detectors failed to catch</h2>
      <p className="mt-1 text-sm text-white/50">
        Every manipulated scenario carries ground truth by construction, so a miss is provable.
        Click one to drill into the order book.
      </p>
      {allMisses.length === 0 ? (
        <div className="mt-4 rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-200">
          No misses — both detectors caught every injected spoof for this set. Try the{" "}
          <span className="mono">flock</span> provider or a different seed to surface divergence.
        </div>
      ) : (
        <div className="mt-4 grid grid-cols-1 gap-4 lg:grid-cols-2">
          <ul className="space-y-2">
            {allMisses.map((m, i) => (
              <li key={`${m.detector_id}-${m.scenario_id}-${i}`}>
                <button
                  onClick={() => onSelect(m.scenario_id)}
                  className={`w-full rounded-lg border p-3 text-left text-sm transition ${
                    selected === m.scenario_id
                      ? "border-sky-400/60 bg-sky-500/10"
                      : "border-white/10 bg-white/[0.03] hover:border-white/25"
                  }`}>
                  <div className="flex items-center justify-between">
                    <span className="mono text-white/80">{m.scenario_id}</span>
                    <span className="mono text-[11px] text-white/40">{m.detector_id}</span>
                  </div>
                  <div className="mt-1 text-xs text-white/50">
                    missed {m.manipulation_type}
                  </div>
                </button>
              </li>
            ))}
          </ul>
          <div>{scenario ? <OrderBook scenario={scenario} /> : <DrillPlaceholder />}</div>
        </div>
      )}
    </section>
  );
}

function DrillPlaceholder() {
  return (
    <div className="flex h-full min-h-[200px] items-center justify-center rounded-lg border border-dashed border-white/15 p-6 text-sm text-white/30">
      Select a miss to inspect its order book.
    </div>
  );
}

function OrderBook({ scenario }: { scenario: Scenario }) {
  const implicated = new Set(scenario.ground_truth.implicated_event_ids);
  return (
    <div className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
      <div className="mb-2 text-sm">
        <span className="mono text-white/80">{scenario.scenario_id}</span>
        <span className="ml-2 text-white/40">· {scenario.market}</span>
      </div>
      <div className="mb-3 rounded-lg border border-amber-400/30 bg-amber-400/10 p-3 text-xs leading-relaxed text-amber-100">
        <span className="font-semibold">Ground truth:</span> {scenario.ground_truth.explanation}
      </div>
      <div className="max-h-72 overflow-auto rounded-lg border border-white/5">
        <table className="w-full text-left text-xs">
          <thead className="sticky top-0 bg-black/50 text-white/40">
            <tr>
              <th className="px-2 py-1.5">ts</th>
              <th className="px-2 py-1.5">type</th>
              <th className="px-2 py-1.5">side</th>
              <th className="px-2 py-1.5 text-right">price</th>
              <th className="px-2 py-1.5 text-right">size</th>
              <th className="px-2 py-1.5">owner</th>
            </tr>
          </thead>
          <tbody className="mono">
            {scenario.events.map((e) => {
              const flag = implicated.has(e.event_id);
              return (
                <tr key={e.event_id}
                  className={flag ? "bg-red-500/15 text-red-100" : "odd:bg-white/[0.02]"}>
                  <td className="px-2 py-1 tabular-nums">{e.ts}</td>
                  <td className="px-2 py-1">{flag ? "⚑ " : ""}{e.type}</td>
                  <td className="px-2 py-1">{e.side}</td>
                  <td className="px-2 py-1 text-right tabular-nums">{e.price.toFixed(2)}</td>
                  <td className="px-2 py-1 text-right tabular-nums">{e.size.toFixed(2)}</td>
                  <td className="px-2 py-1 text-white/60">{e.owner_id}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      <div className="mt-2 text-[11px] text-white/35">
        <span className="inline-block h-2 w-2 rounded-sm bg-red-500/60 align-middle" /> implicated
        events ({implicated.size}) — the injected spoof orders.
      </div>
    </div>
  );
}

function WalrusPanel({ seed, count, fraction }: { seed: number; count: number; fraction: number }) {
  const [store, setStore] = useState<"stub" | "walrus">("stub");
  const [att, setAtt] = useState<Attestation | null>(null);
  const [verify, setVerify] = useState<{ result: VerifyResult; exitCode: number } | null>(null);
  const [busy, setBusy] = useState<"" | "attest" | "verify">("");
  const [err, setErr] = useState<string | null>(null);

  async function doAttest() {
    setBusy("attest"); setErr(null); setVerify(null); setAtt(null);
    try {
      const res = await fetch("/api/attest", {
        method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ seed, count, fraction, store }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.stderr || json.error || "attest failed");
      setAtt(json.attestation as Attestation);
    } catch (e) { setErr((e as Error).message); } finally { setBusy(""); }
  }

  async function doVerify() {
    if (!att) return;
    setBusy("verify"); setErr(null);
    try {
      const res = await fetch("/api/verify", {
        method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ attestation: att, store }),
      });
      const json = await res.json();
      if (!json.result) throw new Error(json.error || "verify failed");
      setVerify({ result: json.result as VerifyResult, exitCode: json.exitCode ?? -1 });
    } catch (e) { setErr((e as Error).message); } finally { setBusy(""); }
  }

  return (
    <section className="mt-8 rounded-xl border border-white/10 bg-white/[0.03] p-5">
      <h2 className="text-lg font-semibold">Tamper-evident record (Walrus)</h2>
      <p className="mt-1 text-sm text-white/50">
        Write the scored run to a content-addressed blob store, then verify by re-fetching and
        recomputing the hash. If the bytes were altered, verification fails — the catch-rate
        claim is provable, not just asserted.
      </p>

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <select value={store} onChange={(e) => setStore(e.target.value as "stub" | "walrus")}
          className="rounded-lg border border-white/12 bg-[#0d1117] px-3 py-2 text-sm">
          <option value="stub">stub (offline)</option>
          <option value="walrus">walrus (live testnet)</option>
        </select>
        <button onClick={doAttest} disabled={busy !== ""}
          className="rounded-lg bg-purple-500 px-4 py-2 text-sm font-semibold text-slate-950 transition hover:bg-purple-400 disabled:opacity-50">
          {busy === "attest" ? "Attesting…" : "Attest run"}
        </button>
        <button onClick={doVerify} disabled={!att || busy !== ""}
          className="rounded-lg border border-white/20 px-4 py-2 text-sm font-semibold transition hover:border-white/40 disabled:opacity-40">
          {busy === "verify" ? "Verifying…" : "Verify"}
        </button>
      </div>

      {err && (
        <div className="mt-4 rounded-lg border border-red-500/40 bg-red-500/10 p-3 text-xs text-red-200">
          <span className="mono">{err}</span>
        </div>
      )}

      {att && (
        <div className="mt-4 space-y-1.5 rounded-lg border border-white/10 bg-black/30 p-4 text-xs">
          <Row k="store" v={att.store} />
          <Row k="run_id" v={att.run_id} />
          <Row k="blob_id" v={att.blob_id} />
          <Row k="content_sha256" v={att.content_sha256} />
        </div>
      )}

      {verify && (
        <div className={`mt-3 flex items-center gap-3 rounded-lg border p-4 text-sm ${
          verify.result.verified
            ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-200"
            : "border-red-500/40 bg-red-500/10 text-red-200"
        }`}>
          <span className="text-xl">{verify.result.verified ? "✓" : "✗"}</span>
          <div>
            <div className="font-semibold">
              {verify.result.verified ? "Verified — bytes are intact" : "TAMPER DETECTED — hash mismatch"}
            </div>
            <div className="mono mt-1 text-[11px] opacity-80">
              computed {verify.result.computed_sha256.slice(0, 16)}… {verify.result.verified ? "==" : "≠"}{" "}
              expected {verify.result.expected_sha256.slice(0, 16)}…
            </div>
          </div>
        </div>
      )}
    </section>
  );
}

function Row({ k, v }: { k: string; v: string }) {
  return (
    <div className="flex gap-3">
      <span className="w-28 shrink-0 text-white/40">{k}</span>
      <span className="mono break-all text-white/80">{v}</span>
    </div>
  );
}

function ModelCatalog({ provider }: { provider: "stub" | "flock" }) {
  const [models, setModels] = useState<string[]>([]);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    fetch(`/api/models?provider=${provider}`)
      .then((r) => r.json())
      .then((j) => {
        if (!active) return;
        setModels(j.models ?? []);
        setErr(j.error ?? null);
      })
      .catch((e) => active && setErr(String(e)));
    return () => { active = false; };
  }, [provider]);

  return (
    <section className="mt-8 rounded-xl border border-white/10 bg-white/[0.02] p-5">
      <h2 className="text-sm font-semibold text-white/70">
        Model catalog <span className="mono text-white/40">({provider})</span>
      </h2>
      {err ? (
        <div className="mt-2 text-xs text-amber-300/80">
          {provider === "flock"
            ? "FLock unavailable (account may need a top-up). The stub provider keeps the demo fully offline."
            : err}
        </div>
      ) : (
        <div className="mt-3 flex flex-wrap gap-2">
          {models.map((m) => (
            <span key={m} className="mono rounded-full border border-white/10 bg-white/[0.04] px-2.5 py-1 text-[11px] text-white/70">
              {m}
            </span>
          ))}
        </div>
      )}
    </section>
  );
}
